const certificados = [
  "certificados/Formação Python Fundamentals.pdf",
  "certificados/Fundamentos de Qualidade de Software.pdf",
  "certificados/Versionamento de Código com Git.pdf",
  "certificados/Trabalhando em Equipes Ágeis.pdf",
  "certificados/Trabalhando com Variáveis.pdf",
  "certificados/Trabalhando Com Operadores.pdf",
  "certificados/Trabalhando Com Operadores Lógicos.pdf",
  "certificados/Trabalhando Com Operadores de Comparação.pdf",
  "certificados/Trabalhando com Listas em Python.pdf",
  "certificados/Trabalhando Com Estruturas de Repetição (for, while, do-while).pdf",
  "certificados/Trabalhando Com Estruturas de Decisão (Estrutura Switch Case).pdf",
  "certificados/Trabalhando Com Estruturas Condicionais (if, else if, else).pdf",
  "certificados/Tipos de Operadores com Python.pdf",
  "certificados/Prompts Assertivos para ChatGPT.pdf",
  "certificados/Programação Orientada a Objetos com Python.pdf",
  "certificados/Princípios de Desenvolvimento de Software Colaborativo.pdf",
  "certificados/Princípios de Desenvolvimento Ágil e Colaborativo.pdf",
  "certificados/Pilares da Programação Orientada a Objetos em Java.pdf",
  "certificados/Onboarding- Conhecendo a Formação ChatGPT for Devs.pdf",
  "certificados/Manipulando Strings com Python.pdf",
  "certificados/Manipulando Arquivos em Python.pdf",
  "certificados/Lógica e Pensamento Computacional.pdf",
  "certificados/Lidando com Data, Hora e Fuso Horário no Python.pdf",
  "certificados/Java e Tratamento de Exceções.pdf",
  "certificados/Introdução e Estruturas Condicionais com Java.pdf",
  "certificados/Introdução as Estruturas de Controle.pdf",
  "certificados/Introdução aos Conceitos Básicos em Lógica de Programação.pdf",
  "certificados/Introdução ao Mercado de Qualidade de Software.pdf",
  "certificados/Introdução ao Desenvolvimento Web com JavaScript.pdf",
  "certificados/Introdução ao Desenvolvimento Moderno de Software.pdf",
  "certificados/Introdução à Programação Orientada a Objetos (POO) com Python.pdf",
  "certificados/Introdução à Plataforma Java.pdf",
  "certificados/Introdução a Lógica.pdf",
  "certificados/Interfaces e Classes Abstratas com Python.pdf",
  "certificados/Importação e Exportação com JavaScript.pdf",
  "certificados/Ganhando Produtividade com Stream API.pdf",
  "certificados/Fundamentos do Python.pdf",
  "certificados/Fundamentos de Qualidade de Software.pdf",
  "certificados/Fundamentos da Programação Orientada a Objetos com Java.pdf",
  "certificados/Explorando Conjuntos em Python.pdf",
  "certificados/Estruturas Condicionais e de Repetição em Python.pdf",
  "certificados/Estrutura de um Software e Seu Ambiente de Desenvolvimento.pdf",
  "certificados/Entendendo Operadores.pdf",
  "certificados/Entendendo Algoritmos e Fluxogramas.pdf",
  "certificados/Dominando o Protocolo HTTP e Integrando com a PokeAPI.pdf",
  "certificados/Dominando Funções Python.pdf",
  "certificados/Dominando Estruturas de Controle.pdf",
  "certificados/Dominando a Linguagem de Programação Java.pdf",
  "certificados/Decoradores, Iteradores e Manipulação de Data e Arquivos em Python.pdf",
  "certificados/Decoradores, Iteradores e Geradores com Python.pdf",
  "certificados/Debugging Java.pdf",
  "certificados/Criando Objetos e Classes em JavaScript.pdf",
  "certificados/Conhecendo Tuplas em Python.pdf",
  "certificados/Conhecendo Polimorfismo em Python.pdf",
  "certificados/Conhecendo Funções JavaScript.pdf",
  "certificados/Conhecendo Collections Java.pdf",
  "certificados/ChatGPT - O Essencial.pdf",
  "certificados/Arrays e Estruturas de Repetição em JavaScript.pdf",
  "certificados/Aprendendo o Conceito de Herança com Python.pdf",
  "certificados/Aprendendo Estruturas de Dados com Python.pdf",
  "certificados/Aprendendo a Utilizar Dicionários em Python.pdf",
  "certificados/Aprendendo a Sintaxe Java.pdf",
  "certificados/Aplicando Encapsulamento em Python.pdf",
  "certificados/Ambiente de Desenvolvimento Java.pdf",
  "certificados/Ambiente de Desenvolvimento e Primeiros Passos com Python.pdf",
  "certificados/Act Commands.pdf",
  // Adicione todos os arquivos manualmente
];

export default certificados;
